### ISSUE TITLE
No notification about received messages in the chat

### ISSUE THREAD

**Issue by DocBox12** [Horndev/zapread.com#249]
**Describe the bug**
If user received message in chat the notification isn't visible.

**To Reproduce**
1. Send message to other user
2. Ask he whether he received notification

**Expected behavior**
After received message in chat icon should be change 

**Desktop (please complete the following information):**
- opensuse Tumbleweed
- Google Chrome

**Smartphone (please complete the following information):**
I'm not tested this bug in mobile devices

**Comment by Horndev** [comment]
Ensure the other user has notifications turned on.

![image](https://user-images.githubusercontent.com/908867/52974698-dd28e080-3398-11e9-9ca3-d2ae3f3df37d.png)

Otherwise, an email will not be sent.  I'm also fixing a bug on mentions in comment replies not working - so it may also be related to that.

**Comment by Horndev** [comment]
Bug fixed.  Should work now.
